bot_token = "1871490605:AAGh44PpJb6c3_ya4OxHa5IRQMXLqHA6GDo"
bot_user_name = "Weather_Station_Dashboard_Bot"
URL = ""
firebase_token = "K4hlhmmLMDg4ssgqtr0TVgyX7jgN16zMfY8eZaNV"
firebase_authDomain = "weather-station-91122.firebaseapp.com"
firebase_databaseURL = "https://weather-station-91122-default-rtdb.firebaseio.com"
firebase_storageBucket = "weather-station-91122.appspot.com"
